# Generated by Django 3.1.7 on 2021-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('employee', 'Employee'), ('employer', 'Employer'), ('institute', 'Institute')], default='teacher', max_length=10),
        ),
    ]
